spring:
  datasource:
    url: jdbc:h2:mem:hrms_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api
